 Perfil ativo padrão (pode ser sobrescrito por variável de ambiente)
spring.profiles.active=dev

spring.application.name=aula

# Configurações do datasource (comuns a todos os ambientes)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}